# Loading libraries and modules

In [1]:
%pylab qt5

Populating the interactive namespace from numpy and matplotlib


In [2]:
mpl.rcParams['grid.color'] = 'k'
mpl.rcParams['grid.linestyle'] = ':'
mpl.rcParams['grid.linewidth'] = 0.5

In [3]:
import drivers
#reload(drivers.Agilent_EXA)

In [4]:
from importlib import reload
import lib2
from lib2.Measurement import *
from lib2.SingleToneSpectroscopy import *
from lib2 import MeasurementResult
from lib2.FourWaveMixingBase import *

# Single-Tone Spectroscopy


In [21]:
STS = SingleToneSpectroscopy("II-qubit_search", "SPS_old_5-0.5 fF", vna = 'vna2', src = 'yok1')
vna_parameters = {"bandwidth":50, "freq_limits":(4000e6, 5000e6), "nop":401, "power":-35, "averages":1}
STS.set_fixed_parameters(vna_parameters)
STS.set_swept_parameters({'current': (STS._src.set_current, linspace(-1e-3, 1e-3, 201))})
result = STS.launch()
result.visualize()

vna2 is already initialized
yok1 is already initialized
Started at:  2017-05-02 22:27:39.279235


C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\backend_bases.py:2445: MatplotlibDeprecationWarning: Using default event loop until function specific to this GUI is implemented
  warnings.warn(str, mplDeprecation)


Time left: 0 h 14 m 24.73 s, current: -1.50e-04]: , average cycle time: 7.52 s       

_______________

## Four Wave mixing Continuous

In [1]:
reload(drivers.E8257D);

NameError: name 'reload' is not defined

In [12]:
# reload(lib2.Measurement)
reload(lib2.FourWaveMixingBase)
from lib2.FourWaveMixingBase import *

In [12]:
vna2 = meas._actual_devices['vna2']

In [ ]:
WMM.close_devs(['exa','mxg','exg'])

In [13]:
WMM = FourWaveMixingBase('I-Measurement_with_2_gens', 'SPS_old', 60, exa = 'exa', src_plus = 'mxg', src_minus = 'exg')

exa is already initialized
mxg is already initialized
exg is already initialized
Enter your comment: test


In [14]:
exa_pars = {"bandwidth":2, "nop":501, "centerfreq":4.2825e9, "span":50e3, "averages":30, "avg_status":1}
WMM.set_fixed_parameters(exa_pars,delta = 1e3)

In [15]:
powers = linspace(-29,9,81)
WMM.set_swept_parameters(WMM.powers_equal_setter_with_offset,powers)

In [ ]:
result = WMM.launch()

Started at:  2017-05-02 22:56:26.184266


C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\backend_bases.py:2445: MatplotlibDeprecationWarning: Using default event loop until function specific to this GUI is implemented
  warnings.warn(str, mplDeprecation)


Time left: 0 h 37 m 44.76 s, powers at $\omega_{p}$: -2.76e+01]: , average cycle time: 29.41 s       

In [40]:
WMM._src_minus.set_output_state("OFF")

In [8]:
list(WMM._actual_devices)

['exa', 'mxg', 'exg']

In [16]:
result.visualize()

In [39]:
plt.plot(Z[Z!=0][-len(fr):-1])

In [31]:
Zr = reshape(Z[Z!=0], (len(fr),-1))[:,-1]

In [34]:
Z[Z!=0]

array([-115.163414  , -112.99225616, -112.55041504, ..., -112.48479462,
       -115.48749542, -114.99030304])

In [29]:
WMM.done_iterations

AttributeError: 'FourWaveMixingBase' object has no attribute 'done_iterations'

In [25]:
Z = real(result.get_data()["data"])
fr = real(result.get_data()["frequency"])
#reshape(Z[Z!=0], (1001,-1))

______________

In [ ]:
plt.margins()

In [ ]:
vna2 = meas._actual_devices['vna2']
yok = meas._actual_devices['yok1']

In [ ]:
yok.set_current_limits(-12e-3,12e-3)

In [2]:
WMM._actual_deices.vna2.del_all_meas()

NameError: name 'WMM' is not defined

In [ ]:
vna2.define_Sij(4,3)

In [ ]:
STS = SingleToneSpectroscopy("I-STS_try_on-PXI", "SPS_old", "current", yok.set_current, vna_name='vna2')
vna_parameters = {"bandwidth":100, "freq_limits":(4e9,6e9), "nop":251, "power":-40, "averages":1}
STS.setup_control_parameters(vna_parameters, linspace(-1e-3, 2e-3, 151))
result = STS.launch()
result.visualize()

In [24]:
result = MeasurementResult("I-STS_try_on-PXI", "SPS_old")

In [27]:
self.

AttributeError: 'MeasurementResult' object has no attribute '_context'

In [30]:
meas._context().get_equipment()

AttributeError: 'Measurement' object has no attribute '_context'

In [30]:
WMM.



TypeError: __repr__ returned non-string (type TCPIPInstrument)

In [5]:
meas = Measurement('1','2',devs_names=['exa',None])

The device exa is detected as EXA


In [14]:
exa

In [13]:
exa._visainstrument.write("INIT:CONT 0")

(13, <StatusCode.success: 0>)

In [12]:
exa.get_averaging_setup()

'EXP'

In [6]:
parameters = {"bandwidth":2e3, "nop":1001, "centerfreq":5e9, "span":1e6, "averages":100, "avg_status":1}

In [7]:
meas._actual_devices['exa'].set_parameters(parameters)

In [ ]:
Measurement._actual_devices['exa'].make_sweep_get_data()

In [7]:
meas._actual_devices

{'exa': <drivers.Agilent_EXA.Agilent_EXA_N9010A at 0x9b2f358>}

In [13]:
meas._actual_devices

{}

In [16]:
exa.make_sweep_get_data()

array([-107.16973114, -107.21291351, -106.55196381, ..., -105.78205872,
       -106.40785217, -106.42636108])

In [108]:
reload(lib2.Measurement)

<module 'lib2.Measurement' from 'C:\\Users\\PAINMASTER\\Measurement\\lib2\\Measurement.py'>

In [12]:
meas = Measurement('1','2',devs_names=['exa'])

exa is already initialized


In [12]:
meas.close_devs(['exa'])

In [38]:

list1 = [1,2,3,4]
list2 = [5,6,7,8]
l = [list1,list2]
list(product(*l))

[(1, 5),
 (1, 6),
 (1, 7),
 (1, 8),
 (2, 5),
 (2, 6),
 (2, 7),
 (2, 8),
 (3, 5),
 (3, 6),
 (3, 7),
 (3, 8),
 (4, 5),
 (4, 6),
 (4, 7),
 (4, 8)]

In [133]:
raw_data = [[(i - j) for j in range(3)] for i in range(3)]

In [95]:
for i in range(len(raw_data)):
    for j in range(len(raw_data[0])):
        raw_data[i,j] = i + j

In [134]:
rd = array(raw_data)

In [135]:
def set_swept_parameters(*powers):
    

array([[ 0, -1, -2],
       [ 1,  0, -1],
       [ 2,  1,  0]])

In [137]:
rd[:,2]

array([-2, -1,  0])

In [61]:
l[2].__index__()-1

3

In [62]:
[i for i,x in enumerate(l)]

[0, 1, 2]

In [63]:
l = [1,2,3,4]

In [65]:
list(range(len(l)))

[0, 1, 2, 3]

In [79]:
pow1 = [1,2,3,4]
pow2 = [5,6,7,8]

In [99]:
a.__keys__

AttributeError: 'zip' object has no attribute '__keys__'

In [91]:
def powers(*powers):
    return list(zip(*powers))

In [95]:
def setter(*powers):
    print(*powers)

In [96]:
parameter_values = powers(pow1,pow2)

In [97]:
for parameter_value in parameter_values:
    setter(parameter_value)

(1, 5)
(2, 6)
(3, 7)
(4, 8)


In [25]:
{"powers_plus_minus": (powers_setter, zip(pow1, pow2))}

NameError: name 'self' is not defined

In [24]:
fig = plt.figure(figsize = (18,6))

In [21]:
ax3 = plt.subplot2grid((4, 4), (0, 0), colspan = 4, rowspan = 1)
ax2 = plt.subplot2grid((4, 4), (1, 0), colspan = 4, rowspan = 3)

In [243]:
ax1.ticklabel_format()

In [20]:
plt.tight_layout()

In [245]:
colorbar.make_axes(ax2, fraction = 0.05)

(<matplotlib.axes._axes.Axes at 0xecdd400>,
 {'orientation': 'vertical', 'ticklocation': 'right'})

C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\figure.py:1742: UserWarning: This figure includes Axes that are not compatible with tight_layout, so its results might be incorrect.
  warnings.warn("This figure includes Axes that are not "


In [6]:
from datetime import datetime

In [10]:
print(datetime.now())

2017-04-28 23:01:00.895048


In [ ]:
def DT_now():
        return str(datetime.now().replace(microsecond=0))