# Loading libraries and modules

In [2]:
%pylab qt5

Populating the interactive namespace from numpy and matplotlib


In [3]:
mpl.rcParams['grid.color'] = 'k'
mpl.rcParams['grid.linestyle'] = ':'
mpl.rcParams['grid.linewidth'] = 0.5

In [4]:
import drivers
#reload(drivers.Agilent_EXA)

In [5]:
from importlib import reload
import lib2
from lib2.Measurement import *
from lib2.SingleToneSpectroscopy import *
from lib2 import MeasurementResult

# Single-Tone Spectroscopy


In [17]:
reload(lib2.Measurement)
reload(drivers.Agilent_EXA)

<module 'drivers.Agilent_EXA' from 'C:\\Users\\PAINMASTER\\Measurement\\drivers\\Agilent_EXA.py'>

In [31]:
meas = Measurement('I-try_on-PXI','SPS_old',devs_names=['vna2','yok1'])

vna2 is already initialized
yok1 is already initialized


______________

In [ ]:
i,j = ,4

In [ ]:
vna2 = meas._actual_devices['vna2']
yok = meas._actual_devices['yok1']

In [ ]:
yok.set_current_limits(-12e-3,12e-3)

In [ ]:
vna2.del_all_meas()

In [ ]:
vna2.define_Sij(4,3)

In [ ]:
STS = SingleToneSpectroscopy("I-STS_try_on-PXI", "SPS_old", "current", yok.set_current, vna_name='vna2')
vna_parameters = {"bandwidth":100, "freq_limits":(4e9,6e9), "nop":251, "power":-40, "averages":1}
STS.setup_control_parameters(vna_parameters, linspace(-1e-3, 2e-3, 151))
result = STS.launch()
result.visualize()

In [24]:
result = MeasurementResult("I-STS_try_on-PXI", "SPS_old")

In [27]:
result.get_context()

AttributeError: 'MeasurementResult' object has no attribute '_context'

In [30]:
meas._context().get_equipment()

AttributeError: 'Measurement' object has no attribute '_context'

In [35]:
meas._actual_devices[]

KeyError: ''

In [6]:
meas = Measurement('1','2',devs_names=['exa', None])

The device exa is detected as EXA


In [9]:
Measurement._actual_devices

{}

In [8]:
meas.close_devs(['exa'])

In [14]:
meas._actual_devices['exa']._visainstrument.close()

In [17]:
meas._actual_devices

{}

In [93]:
d = {'1': 1, '2':2}

In [107]:
meas3

{'2': 2}

In [108]:
reload(lib2.Measurement)

<module 'lib2.Measurement' from 'C:\\Users\\PAINMASTER\\Measurement\\lib2\\Measurement.py'>

In [12]:
meas = Measurement('1','2',devs_names=['exa'])

exa is already initialized


In [13]:
meas._actual_devices

{'exa': <drivers.Agilent_EXA.Agilent_EXA_N9010A at 0x93c5208>}

In [15]:
meas.close_devs(['exa'])

TypeError: close_devs() takes 1 positional argument but 2 were given

In [12]:
a = [1,2]
b = [3]
for i,j in zip(a,b):
    print(i,j)

1 3


In [28]:
d = {'1': np.linspace(0,10,11), '2': 2}

In [30]:
d['1']

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.])

In [33]:
if '3' in d.keys():
    print(1)

In [35]:
for key, value in d.items():
    print(key, value)

1 [  0.   1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]
2 2


In [36]:
from itertools import product

In [38]:

list1 = [1,2,3,4]
list2 = [5,6,7,8]
l = [list1,list2]
list(product(*l))

[(1, 5),
 (1, 6),
 (1, 7),
 (1, 8),
 (2, 5),
 (2, 6),
 (2, 7),
 (2, 8),
 (3, 5),
 (3, 6),
 (3, 7),
 (3, 8),
 (4, 5),
 (4, 6),
 (4, 7),
 (4, 8)]

In [133]:
raw_data = [[(i - j) for j in range(3)] for i in range(3)]

In [95]:
for i in range(len(raw_data)):
    for j in range(len(raw_data[0])):
        raw_data[i,j] = i + j

In [134]:
rd = array(raw_data)

In [135]:
rd

array([[ 0, -1, -2],
       [ 1,  0, -1],
       [ 2,  1,  0]])

In [137]:
rd[:,2]

array([-2, -1,  0])

In [61]:
l[2].__index__()-1

3

In [62]:
[i for i,x in enumerate(l)]

[0, 1, 2]

In [63]:
l = [1,2,3,4]

In [65]:
list(range(len(l)))

[0, 1, 2, 3]