# Loading libraries and modules

In [1]:
%pylab qt5

Populating the interactive namespace from numpy and matplotlib


In [2]:
mpl.rcParams['grid.color'] = 'k'
mpl.rcParams['grid.linestyle'] = ':'
mpl.rcParams['grid.linewidth'] = 0.5

In [3]:
import drivers
#reload(drivers.Agilent_EXA)

In [4]:
from importlib import reload
import lib2
from lib2.Measurement import *
from lib2.SingleToneSpectroscopy import *
from lib2 import MeasurementResult

# Single-Tone Spectroscopy


In [ ]:
reload(lib2.Measurement)
reload(drivers.Agilent_EXA)

In [31]:
meas = Measurement('I-try_on-PXI','SPS_old',devs_names=['vna2','yok1'])

vna2 is already initialized
yok1 is already initialized


______________

In [ ]:
i,j = ,4

In [ ]:
vna2 = meas._actual_devices['vna2']
yok = meas._actual_devices['yok1']

In [ ]:
yok.set_current_limits(-12e-3,12e-3)

In [ ]:
vna2.del_all_meas()

In [ ]:
vna2.define_Sij(4,3)

In [ ]:
STS = SingleToneSpectroscopy("I-STS_try_on-PXI", "SPS_old", "current", yok.set_current, vna_name='vna2')
vna_parameters = {"bandwidth":100, "freq_limits":(4e9,6e9), "nop":251, "power":-40, "averages":1}
STS.setup_control_parameters(vna_parameters, linspace(-1e-3, 2e-3, 151))
result = STS.launch()
result.visualize()

In [24]:
result = MeasurementResult("I-STS_try_on-PXI", "SPS_old")

In [27]:
result.get_context()

AttributeError: 'MeasurementResult' object has no attribute '_context'

In [30]:
meas._context().get_equipment()

AttributeError: 'Measurement' object has no attribute '_context'

In [26]:
meas.close_devs(['exa'])

In [5]:
meas = Measurement('1','2',devs_names=['exa',None])

The device exa is detected as EXA


In [14]:
exa

In [13]:
exa._visainstrument.write("INIT:CONT 0")

(13, <StatusCode.success: 0>)

In [12]:
exa.get_averaging_setup()

'EXP'

In [6]:
parameters = {"bandwidth":2e3, "nop":1001, "centerfreq":5e9, "span":1e6, "averages":100, "avg_status":1}

In [7]:
meas._actual_devices['exa'].set_parameters(parameters)

In [ ]:
Measurement._actual_devices['exa'].make_sweep_get_data()

In [7]:
meas._actual_devices

{'exa': <drivers.Agilent_EXA.Agilent_EXA_N9010A at 0x9b2f358>}

In [13]:
meas._actual_devices

{}

In [16]:
exa.make_sweep_get_data()

array([-107.16973114, -107.21291351, -106.55196381, ..., -105.78205872,
       -106.40785217, -106.42636108])

In [108]:
reload(lib2.Measurement)

<module 'lib2.Measurement' from 'C:\\Users\\PAINMASTER\\Measurement\\lib2\\Measurement.py'>

In [12]:
meas = Measurement('1','2',devs_names=['exa'])

exa is already initialized


In [12]:
meas.close_devs(['exa'])

In [38]:

list1 = [1,2,3,4]
list2 = [5,6,7,8]
l = [list1,list2]
list(product(*l))

[(1, 5),
 (1, 6),
 (1, 7),
 (1, 8),
 (2, 5),
 (2, 6),
 (2, 7),
 (2, 8),
 (3, 5),
 (3, 6),
 (3, 7),
 (3, 8),
 (4, 5),
 (4, 6),
 (4, 7),
 (4, 8)]

In [133]:
raw_data = [[(i - j) for j in range(3)] for i in range(3)]

In [95]:
for i in range(len(raw_data)):
    for j in range(len(raw_data[0])):
        raw_data[i,j] = i + j

In [134]:
rd = array(raw_data)

In [135]:
rd

array([[ 0, -1, -2],
       [ 1,  0, -1],
       [ 2,  1,  0]])

In [137]:
rd[:,2]

array([-2, -1,  0])

In [61]:
l[2].__index__()-1

3

In [62]:
[i for i,x in enumerate(l)]

[0, 1, 2]

In [63]:
l = [1,2,3,4]

In [65]:
list(range(len(l)))

[0, 1, 2, 3]